# Generated by Django 4.2.17 on 2024-12-25 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_clientactions_alter_profile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientActions',
        ),
    ]
