# Generated by Django 4.2.17 on 2025-01-08 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_cart_items_cart_products_cart_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
