# Generated by Django 4.2.17 on 2025-02-19 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_offer_product_off_alter_product_image_product_offers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='off',
        ),
        migrations.RemoveField(
            model_name='product',
            name='offers',
        ),
        migrations.DeleteModel(
            name='Offer',
        ),
    ]
